#!/usr/bin/env bash
set -euo pipefail

CACHED_DB=${XDG_CACHE_HOME:-~/.cache}/wofi-emoji.db

if [ ! -f "$CACHED_DB" ]
then
  if ! curl --fail-with-body https://raw.githubusercontent.com/muan/emojilib/v3.0.12/dist/emoji-en-US.json \
    | jq --raw-output '. | to_entries | .[] | .key + " " + (.value | join(" ") | sub("_"; " "; "g"))' \
    > "$CACHED_DB"
    then
      echo "Failed to download emoji db"
      rm "$CACHED_DB"
      exit 1
  fi
fi

EMOJI="$(wofi -p "emoji" --show dmenu -i < "$CACHED_DB" | cut -d ' ' -f 1 | tr -d '\n')"
wtype "$EMOJI"; wl-copy "$EMOJI"
