#!/usr/bin/env bash
set -euo pipefail

CONFIG_FILE=~/.config/wofi-emoji.rc
EMOJI="$(cat $CONFIG_FILE | wofi -p "emoji" --show dmenu -i | cut -d ' ' -f 1 | tr -d '\n')"
wtype "$EMOJI"; wl-copy "$EMOJI"
exit
